version: "3"

services:
  web:
    image: misskey/misskey:13.13.2
    restart: always
    links:
      - db
      - redis
    volumes:
      - ./files:/misskey/files
      - ./.config/default.yml:/misskey/.config/default.yml:ro

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    links:
      - web
    volumes:
      - ./nginx/misskey.conf:/etc/nginx/conf.d/misskey.conf
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
